---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Juniper IPs
  hosts: juniper
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    - name: Delete default security zones
      junipernetworks.junos.junos_security_zones:
        config:
          zones:
            - name: zone
            - juniper-host
        state: deleted

    - name: Create security zones
      junipernetworks.junos.junos_security_zones:
        config:
          zones: "{{ security_zones }}"
        state: merged

    - name: Create security policies
      junipernetworks.junos.junos_security_policies:
        config: "{{ security_policies }}"
        state: overridden

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true
    # - name: Rollback Juniper OS to last commit
    #   junipernetworks.junos.junos_config:
    #     rollback: 0
    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true

