---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Juniper setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

  - name: Set Juniper password
    ansible.builtin.expect:
      command: "ssh -o StrictHostKeyChecking=no -i /tmp/private-key.pem {{ ec2_juniper_user }}@{{ groups['juniper'][0] }}"
      responses:
        'ec2-user> ':
          - "configure"
          - "exit"
          - "exit"
        'ec2-user# ':
          # - "set groups aws-default system host-name Juniper-1"
          - "set groups aws-default system login user ec2-user class super-user"
          - "set groups aws-default system services ssh no-passwords"
          - "delete groups aws-default system services ssh no-passwords"
          - "set groups aws-default system authentication-order password"
          - "set groups aws-default system login user ec2-user authentication encrypted-password {{ hashed_password }}"
          - "set groups aws-default security forwarding-options family mpls mode packet-based"
          - "set groups aws-default security forwarding-options family iso mode packet-based"
          - "commit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
    no_log: false # hide passwords on logs
