---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Juniper setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
  # cat private-key.pem | ansible-vault encrypt_string  --stdin-name 'private_key' --output private-key.vault
  - ansible.builtin.include_vars: files/private-key.yml

  - name: Copy private key locally
    ansible.builtin.copy:
      content: "{{ private_key }}"
      dest: /tmp/private-key.pem
      mode: '0600'

  - ansible.builtin.set_fact:
      my_salt: "{{ 99999999 | random | to_uuid | regex_replace('-', '') | truncate(15, True, '') }}"

  - ansible.builtin.set_fact:
      hashed_password: "{{ ec2_juniper_pass | password_hash('sha512', my_salt) }}"

  - name: Set Juniper password
    ansible.builtin.expect:
      command: "ssh -o StrictHostKeyChecking=no -i /tmp/private-key.pem {{ ec2_juniper_user }}@{{ groups['juniper'][0] }}"
      responses:
        'ec2-user> ':
          - "configure"
          - "exit"
          - "exit"
        'ec2-user# ':
          # - "set groups aws-default system host-name Juniper-1"
          - "set groups aws-default system login user ec2-user class super-user"
          - "set groups aws-default system services ssh no-passwords"
          - "delete groups aws-default system services ssh no-passwords"
          - "set groups aws-default system authentication-order password"
          - "set groups aws-default system login user ec2-user authentication encrypted-password {{ hashed_password }}"
          - "commit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
          - "exit"
    no_log: false # hide passwords on logs
