---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Collect Juniper Facts
  hosts: juniper
  gather_facts: false
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    - name: JunOS Facts
      junipernetworks.junos.junos_facts:
        gather_subset: 
          - "all"
          # - "!config"
        gather_network_resources:
      register: _junos_facts

    - debug: 
        var: _junos_facts

